### ISSUE TITLE
Train Attribute Module

### ISSUE THREAD

**Issue by yihang-xdu** [whcpumpkin/Demand-driven-navigation#3]
Dear Authors,

Thanks for your great work!  I meet an error when I run ' python train_attribute_features.py --epoch=5000 ' to train a attribute module :

Traceback (most recent call last):
  File "/data1/zyh/Demand-driven-navigation-main/train_attribute_features.py", line 201, in <module>
    main()
  File "/data1/zyh/Demand-driven-navigation-main/train_attribute_features.py", line 195, in main
    global_step, avg_loss, min_val_epoch, min_val_loss = train(args, train_dataset, val_dataset, model)
  File "/data1/zyh/Demand-driven-navigation-main/train_attribute_features.py", line 97, in train
    val_loss = eval(args, model, val_dataloader)
  File "/data1/zyh/Demand-driven-navigation-main/train_attribute_features.py", line 129, in eval
    return global_loss/global_step
ZeroDivisionError: float division by zero

When I debug it, I find  the code ' val_dataset = instruction_LGO_dataset(args, "val") ' get a empty self.instruction, that is because: ' self.instruction = set(self.instruction.keys()).intersection(set(self.instruction_features.keys())).intersection(set(self.LGO_features.keys())) '
the intersection of the three is empty. 

Can you give me some advice? Thank you again!

**Comment by whcpumpkin** [comment]
Hi,
Try this command
`python train_attribute_features.py --epoch=5000 --args.path2instruction_bert_features=./dataset/instruction_bert_features.json`

**Comment by yihang-xdu** [comment]
Dear Authors,

Thanks for your reply !  I think this may not be a problem of not reading the json file. When I read the file "instruction_val_check.json" , I get 241 dictionaries , and before the the intersection of the three ,  it still has 239 dictionaries .
But the the the intersection of the three is empty .  I don't know whether the number of it is right .  Can you help me check it?
Here are some details before the intersection of the three :

![2023-12-23_10-12-17](https://github.com/whcpumpkin/Demand-driven-navigation/assets/103943036/96b76a90-951b-4e08-97d8-b025afa0ce04)

**Comment by whcpumpkin** [comment]
> Dear Authors,
> 
> Thanks for your reply ! I think this may not be a problem of not reading the json file. When I read the file "instruction_val_check.json" , I get 241 dictionaries , and before the the intersection of the three , it still has 239 dictionaries . But the the the intersection of the three is empty . I don't know whether the number of it is right . Can you help me check it? Here are some details before the intersection of the three :
> 
> ![2023-12-23_10-12-17](https://private-user-images.githubusercontent.com/103943036/292604350-96b76a90-951b-4e08-97d8-b025afa0ce04.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDMzMTQ0NjcsIm5iZiI6MTcwMzMxNDE2NywicGF0aCI6Ii8xMDM5NDMwMzYvMjkyNjA0MzUwLTk2Yjc2YTkwLTk1MWItNGUwOC05N2Q4LWIwMjVhZmEwY2UwNC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBSVdOSllBWDRDU1ZFSDUzQSUyRjIwMjMxMjIzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDIzMTIyM1QwNjQ5MjdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0yZDA1N2JhNDE3ZWI5ZDljYjcyY2VjYWQ0M2E0NGNjYjYzNWQ2YjliMzI0MGExNzQyODkzNTQ0NDk0OTE3NDU4JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.Vu-i6hOXvMXd1itMBYLH22JL_A1UJcbxI3raI6sAD3M)

Hi,
I am sorry that I uploaded the wrong JSON files. I re-upload the related JSON files just now including `instruction_bert_features.json` and `LGO_feature.json`. Please download them again.

**Comment by yihang-xdu** [comment]
The code works now ! Thanks a lot !

**Comment by tongzhao315** [comment]
![issues](https://github.com/whcpumpkin/Demand-driven-navigation/assets/45264967/776ce506-d8e7-4065-9675-72ca20ad6b85)
Dear Authors,

Thanks for your great work! I meet an error when I run ' python train_attribute_features.py --epoch=5000 ' to train a attribute module :
Please ask the author, if you have ever encountered this problem. Trying to use the debug model, this problem still occurs. The online search indicates that it may be due to the lack of hardware, but I see that your code writes that one gpu can be used, but there are 8 GPUs available on my server

Can you give me some advice? Thank you again!

**Comment by gqsmmz** [comment]
> > Dear Authors,
> > Thanks for your reply ! I think this may not be a problem of not reading the json file. When I read the file "instruction_val_check.json" , I get 241 dictionaries , and before the the intersection of the three , it still has 239 dictionaries . But the the the intersection of the three is empty . I don't know whether the number of it is right . Can you help me check it? Here are some details before the intersection of the three :
> > ![2023-12-23_10-12-17](https://private-user-images.githubusercontent.com/103943036/292604350-96b76a90-951b-4e08-97d8-b025afa0ce04.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDMzMTQ0NjcsIm5iZiI6MTcwMzMxNDE2NywicGF0aCI6Ii8xMDM5NDMwMzYvMjkyNjA0MzUwLTk2Yjc2YTkwLTk1MWItNGUwOC05N2Q4LWIwMjVhZmEwY2UwNC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBSVdOSllBWDRDU1ZFSDUzQSUyRjIwMjMxMjIzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDIzMTIyM1QwNjQ5MjdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0yZDA1N2JhNDE3ZWI5ZDljYjcyY2VjYWQ0M2E0NGNjYjYzNWQ2YjliMzI0MGExNzQyODkzNTQ0NDk0OTE3NDU4JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.Vu-i6hOXvMXd1itMBYLH22JL_A1UJcbxI3raI6sAD3M)
> 
> Hi, I am sorry that I uploaded the wrong JSON files. I re-upload the related JSON files just now including `instruction_bert_features.json` and `LGO_feature.json`. Please download them again.

hello, `LGO_feature.json` in [Googledrive](https://drive.google.com/drive/folders/1iR-zf3SHLMhA05IQXsQGUfyfB-8spFC-?usp=sharing) still has the problem as  belows:

$python train_attribute_features.py --epoch=5000
Traceback (most recent call last):
  File "/home/datadisk3/lss/demandnav/train_attribute_features.py", line 201, in <module>
    main()
  File "/home/datadisk3/lss/demandnav/train_attribute_features.py", line 195, in main
    global_step, avg_loss, min_val_epoch, min_val_loss = train(args, train_dataset, val_dataset, model)
  File "/home/datadisk3/lss/demandnav/train_attribute_features.py", line 97, in train
    val_loss = eval(args, model, val_dataloader)
  File "/home/datadisk3/lss/demandnav/train_attribute_features.py", line 129, in eval
    return global_loss/global_step
ZeroDivisionError: float division by zero

And The link to Onedrive has failed.

Is it because the `LGO_feature.json` on GoogleDrive has not been updated to the correct file yet， can you upload the updated  `LGO_feature.json` ?

Look forward to your reply！~

**Comment by whcpumpkin** [comment]
> > > Dear Authors,
> > > Thanks for your reply ! I think this may not be a problem of not reading the json file. When I read the file "instruction_val_check.json" , I get 241 dictionaries , and before the the intersection of the three , it still has 239 dictionaries . But the the the intersection of the three is empty . I don't know whether the number of it is right . Can you help me check it? Here are some details before the intersection of the three :
> > > ![2023-12-23_10-12-17](https://private-user-images.githubusercontent.com/103943036/292604350-96b76a90-951b-4e08-97d8-b025afa0ce04.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDMzMTQ0NjcsIm5iZiI6MTcwMzMxNDE2NywicGF0aCI6Ii8xMDM5NDMwMzYvMjkyNjA0MzUwLTk2Yjc2YTkwLTk1MWItNGUwOC05N2Q4LWIwMjVhZmEwY2UwNC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBSVdOSllBWDRDU1ZFSDUzQSUyRjIwMjMxMjIzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDIzMTIyM1QwNjQ5MjdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0yZDA1N2JhNDE3ZWI5ZDljYjcyY2VjYWQ0M2E0NGNjYjYzNWQ2YjliMzI0MGExNzQyODkzNTQ0NDk0OTE3NDU4JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.Vu-i6hOXvMXd1itMBYLH22JL_A1UJcbxI3raI6sAD3M)
> > 
> > 
> > Hi, I am sorry that I uploaded the wrong JSON files. I re-upload the related JSON files just now including `instruction_bert_features.json` and `LGO_feature.json`. Please download them again.
> 
> hello, `LGO_feature.json` in [Googledrive](https://drive.google.com/drive/folders/1iR-zf3SHLMhA05IQXsQGUfyfB-8spFC-?usp=sharing) still has the problem as belows:
> 
> $python train_attribute_features.py --epoch=5000 Traceback (most recent call last): File "/home/datadisk3/lss/demandnav/train_attribute_features.py", line 201, in main() File "/home/datadisk3/lss/demandnav/train_attribute_features.py", line 195, in main global_step, avg_loss, min_val_epoch, min_val_loss = train(args, train_dataset, val_dataset, model) File "/home/datadisk3/lss/demandnav/train_attribute_features.py", line 97, in train val_loss = eval(args, model, val_dataloader) File "/home/datadisk3/lss/demandnav/train_attribute_features.py", line 129, in eval return global_loss/global_step ZeroDivisionError: float division by zero
> 
> And The link to Onedrive has failed.
> 
> Is it because the `LGO_feature.json` on GoogleDrive has not been updated to the correct file yet， can you upload the updated `LGO_feature.json` ?
> 
> Look forward to your reply！~

Hi,
I am sorry that the link of onedrive was down. The data in googledrive is not as new as in onedrive.
I have updated the` LGO_feature.json` in googledrive just now. 
If you have anyother problem, feel free to ask me.

**Comment by gqsmmz** [comment]
Thanks so much for your reply! and I have another question when I run the Testing period's model selection that, I found  my cuda out of memoy  ( I ran the experiment in 1*4090GPU)。

So I'd like to ask how many cuda memory do the testing periocomput?

through your Testing period's Navigation Policy Testing code, will the AI2thor visualization automatically pop up ? (I run in my headless machine, usually I show the AI2ttho in my local computer through X11 Server)



---- Replied Message ----
| From | ***@***.***> |
| Date | 07/17/2024 20:47 |
| To | ***@***.***> |
| Cc | ***@***.***>***@***.***> |
| Subject | Re: [whcpumpkin/Demand-driven-navigation] Train Attribute Module (Issue #3) |

Dear Authors,
Thanks for your reply ! I think this may not be a problem of not reading the json file. When I read the file "instruction_val_check.json" , I get 241 dictionaries , and before the the intersection of the three , it still has 239 dictionaries . But the the the intersection of the three is empty . I don't know whether the number of it is right . Can you help me check it? Here are some details before the intersection of the three :


Hi, I am sorry that I uploaded the wrong JSON files. I re-upload the related JSON files just now including instruction_bert_features.json and LGO_feature.json. Please download them again.

hello, LGO_feature.json in Googledrive still has the problem as belows:

$python train_attribute_features.py --epoch=5000 Traceback (most recent call last): File "/home/datadisk3/lss/demandnav/train_attribute_features.py", line 201, in main() File "/home/datadisk3/lss/demandnav/train_attribute_features.py", line 195, in main global_step, avg_loss, min_val_epoch, min_val_loss = train(args, train_dataset, val_dataset, model) File "/home/datadisk3/lss/demandnav/train_attribute_features.py", line 97, in train val_loss = eval(args, model, val_dataloader) File "/home/datadisk3/lss/demandnav/train_attribute_features.py", line 129, in eval return global_loss/global_step ZeroDivisionError: float division by zero

And The link to Onedrive has failed.

Is it because the LGO_feature.json on GoogleDrive has not been updated to the correct file yet， can you upload the updated LGO_feature.json ?

Look forward to your reply！~

Hi,
I am sorry that the link of onedrive was down. The data in googledrive is not as new as in onedrive.
I have updated the LGO_feature.json in googledrive just now.
If you have anyother problem, feel free to ask me.

**Comment by gqsmmz** [comment]
Thanks so much, I used the `LGO_feature.json` in googledrive, and changed `args.path2instruction_bert_features` to `./dataset/instruction_bert_features.json`, which helped me run successfully.
